<?php

namespace App\Console\Commands;

use App\Http\Controllers\ImageController;
use Config;
use DB;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Mail;

class DeleteGeneratedVideoSchedule extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'DeleteGeneratedVideo:command';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Delete user generated video after 24 hour';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $result = DB::select('SELECT
                                 id,
                                 output_video,
                                 update_time
                             FROM 
                                  video_template_jobs
                             WHERE
                                  	update_time <= NOW() - INTERVAL 24 HOUR AND 
                                  	status=1 AND 
                                  	NOT isnull(output_video)
                                ORDER BY update_time');

        if (count($result) > 0) {
            foreach ($result as $row) {
                if ($row->output_video != '') {
                    DB::beginTransaction();
                    DB::update('UPDATE video_template_jobs SET output_video = NULL, update_time = update_time WHERE id=?', [$row->id]);
                    DB::commit();

                    if (Config::get('constant.STORAGE') === 'S3_BUCKET') {
                        (new ImageController())->deleteObjectFromS3($row->output_video, 'temp');
                    } else {
                        $original_image_path = './..'.Config::get('constant.TEMP_DIRECTORY').$row->output_video;
                        if (($is_exist = ((new ImageController())->checkFileExist($original_image_path)) != 0)) {
                            unlink($original_image_path);
                        }
                    }
                }
            }
        }

        $template = 'delete_generated_video_report';
        $date = date('Y-m-d');

        if (count($result) <= 0) {
            $subject = "Photoadking:No videos deleted on date $date";
            $message = 'No any user generate video for delete from server.';
        } else {
            $subject = 'Photoadking:'.count($result)." videos deleted on date $date";
            $message = 'Total '.count($result).' videos deleted from server which was generated by user before 24 hours.';
        }

        $message_body = [
            'message' => $message,
        ];

        $data = ['template' => $template, 'subject' => $subject, 'message_body' => $message_body];

        Mail::send($data['template'], $data, function ($message) use ($data) {
            $message->to(Config::get('constant.ADMIN_EMAIL_ID'))->subject($data['subject']);
            $message->bcc(Config::get('constant.SUPER_ADMIN_EMAIL_ID'))->subject($data['subject']);
        });
    }
}
